name: ai-pixel
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip 22.2.2
  - cudatoolkit=11.3
  - pytorch=1.13.0
  - torchvision=0.14.0
  - numpy=1.23.1
  - pip:
        - albumentations==0.4.3
        - opencv-python==4.5.5.64
        - pudb==2019.2
        - imageio==2.9.0
        - imageio-ffmpeg==0.4.2
        - pytorch-lightning==1.4.2
        - omegaconf==2.1.1
        - realesrgan==0.3.0
        - test-tube>=0.7.5
        - pillow==9.2.0
        - einops==0.3.0
        - torch-fidelity==0.3.0
        - transformers==4.19.2
        - torchmetrics==0.6.0
        - kornia==0.6.0
        - PySide6
        - timm
        - numexpr
        - scikit-learn
        - piexif
        - fonts
        - fonts-roboto
        - -e git+https://github.com/openai/CLIP.git@main#egg=clip
        - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
        - -e git+https://github.com/lstein/k-diffusion.git@master#egg=k-diffusion
        - -e git+https://github.com/lstein/GFPGAN@fix-dark-cast-images#egg=gfpgan
        - -e git+https://github.com/xinntao/Real-ESRGAN#egg=realesrgan
        - -e .